name: Music Assistant BETA
version: "2.0.0b6-1"
slug: music_assistant_beta
description: BETA version of Music Assistant. Install this version if you want to keep up with the latest and greatest and don't mind some beta testing. Follow us on discord to report and discuss feedback!
url: https://github.com/music-assistant/hass-music-assistant
arch:
  - amd64
  - aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
map:
- media:rw
init: false
# NOTE: set to advanced when we're out of 2.0 beta
advanced: false
stage: stable
image: ghcr.io/music-assistant/server
tmpfs: true
